name: THE J. SMITH COLLECTION
favicon: null
layout_spectrum: 0.1579432354774326
typography_spectrum: 0.07162079191766679
title: 'Visual therapy '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5643876111134887
  lightness: 0.8777976708952338
  saturation: 0.057121548568829894
  rhythmicContrast: 0.8824310856871307
purpose: []
