name: THE J. SMITH COLLECTION
favicon: null
layout_spectrum: 0.46169
typography_spectrum: 0.15052
title: 'Visual therapy '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aaaaaa'
    - '#ffffff'
    - '#808080'
    - '#575757'
  brandStrength: 0.5643876111134887
  lightness: 0.8777976708952338
  saturation: 0.1875
  rhythmicContrast: 0.8824310856871307
purpose: []
